/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import javax.swing.JOptionPane;



/**
 *
 * @author hp
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
      txt_contraseña.setText("Contraseña");
      txt_email.setText("alguien@example.com");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_iniciar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_registro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        txt_sms = new javax.swing.JLabel();
        txt_sms1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_sms2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicie sesión mediante su cuenta organizativa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        txt_email.setForeground(new java.awt.Color(102, 102, 102));
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emailMouseClicked(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 190, -1));

        btn_iniciar.setBackground(new java.awt.Color(51, 102, 255));
        btn_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        btn_iniciar.setText("Iniciar sesión");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("No se encuentra registrado ?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        btn_registro.setBackground(new java.awt.Color(0, 102, 255));
        btn_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_registro.setText("Registrarse");
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 110, 20));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("DE CAJA CHICA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EPN_logo_big.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("MANEJO Y CONTROL "); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        txt_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_contraseñaMouseClicked(evt);
            }
        });
        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 190, -1));

        txt_sms.setBackground(new java.awt.Color(255, 255, 255));
        txt_sms.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        txt_sms.setForeground(new java.awt.Color(255, 255, 204));
        txt_sms.setToolTipText("");
        txt_sms.setAutoscrolls(true);
        getContentPane().add(txt_sms, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 270, 20));

        txt_sms1.setBackground(new java.awt.Color(255, 255, 255));
        txt_sms1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        txt_sms1.setForeground(new java.awt.Color(255, 255, 204));
        txt_sms1.setToolTipText("");
        txt_sms1.setAutoscrolls(true);
        getContentPane().add(txt_sms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 270, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/esfotpanoramica.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 620, 630));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_esfot.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 260, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-blanco.gif"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 120));

        txt_sms2.setBackground(new java.awt.Color(255, 255, 255));
        txt_sms2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        txt_sms2.setForeground(new java.awt.Color(255, 51, 51));
        txt_sms2.setToolTipText("");
        txt_sms2.setAutoscrolls(true);
        getContentPane().add(txt_sms2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 230, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        // TODO add your handling code here:
        String e=txt_email.getText();
        String c=txt_contraseña.getText();
        if(e.equals("")||c.equals("")){
             txt_sms1.setText("Escriba el identificador de usuario con el formato");
             txt_sms.setText("dominio\\usuario\" o \"usuario@dominio\".");
        }
        else if(c.equals("Contraseña")||e.equals("alguien@example.com")){
            txt_sms1.setText("Escriba el identificador de usuario con el formato");
             txt_sms.setText("dominio\\usuario\" o \"usuario@dominio\".");
        }
        
        
        
        
        else{
            txt_sms1.setText("");
            txt_sms.setText("");
            
            
            
            
        }
      
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        // TODO add your handling code here:
        Registro reg = new Registro();
        reg.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_registroActionPerformed

    private void txt_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMouseClicked
        // TODO add your handling code here:
        String e=txt_email.getText();
        String c=txt_contraseña.getText();
        if(e.equals("alguien@example.com")){
        txt_email.setText("");
        }
    }//GEN-LAST:event_txt_emailMouseClicked

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void txt_contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contraseñaMouseClicked
        // TODO add your handling code here:
        String e=txt_email.getText();
        String c=txt_contraseña.getText();
        if(c.equals("Contraseña")){
        txt_contraseña.setText("");
        }
    }//GEN-LAST:event_txt_contraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_sms;
    private javax.swing.JLabel txt_sms1;
    private javax.swing.JLabel txt_sms2;
    // End of variables declaration//GEN-END:variables
}
